Tarea/donaciones
G5-Squad-Edix/aristopets pull request #21
Opened 2022-04-30 10:45 UTC by palolo25

# Contenidos

La pull request de tarea/donaciones contiene cambios tanto en donaciones como en quienes somos.

### Desplegar el código fuente
Para realizar correctamente la revisión de la `pull-request`, se debe seguir el procedimiento:

1. En el directorio dónde tiene clonado el repositorio (local): `git pull origin tarea/voluntariado`
1. Activar la rama: `git checkout tarea/voluntariado`
1. Instalación de dependencias npm(estando en el directorio del proyecto): `npm install`
1. Levantar la página web en el servidor local: `npm run serve`

_Nota: recuerde que si tenía cambios en su rama local antes de descargar la rama de la `pull-request`, debe confirmarlos_

- [ ] Carpeta img/ no está en la ruta adecua y el nombre no es correcto. Debe estar en assets/images/
- Sección de quienes somos
  - [ ] Cambiar los textos de quienes somos por textos en latín
  - [ ] Eliminar el header de la página sobrante (el que no tiene el menú)
  - [ ] Agregar header al bloque main
  - [ ] Eliminar los id que no sean necesrios
  - [ ] Eliminar los div que no son necesarios (dentro de secciones, etc)
  - [ ] Añadir los figure para contener imágenes e iframes (incluir también figcaption)
  - [ ] Quitar los párrafos (<p/>) de las etiquetas header
  - [ ] Corrregir las filas de tablas (uso de td en vez de tr) y los contenidos puestos
  - [ ] Utilizar correctamente section y etiqueta address, blockquote

2022-05-01 20:17 UTC, aseguragonzalez requested changes
General

- [ ] Carpeta img/ no está en la ruta adecua y el nombre no es correcto. Debe estar en assets/images/donaciones/
- [ ] Corregir todas las rutas de las imagenes de img/ a la ruta adecuada

- Sección de quienes somos
  - [x] Cambiar los textos de quienes somos por textos en latín
  - [ ] Eliminar el header de la página sobrante (el que no tiene el menú)
  - [ ] Agregar header al bloque main
  - [x] Eliminar los id que no sean necesrios
  - [x] Eliminar los div que no son necesarios (dentro de secciones, etc)
  - [ ] Añadir los figure para contener imágenes e iframes (incluir también figcaption)
  - [x] Quitar los párrafos (<p/>) de las etiquetas header
  - [x] Corrregir las filas de tablas (uso de td en vez de tr) y los contenidos puestos
  - [x] Utilizar correctamente section y etiqueta address, blockquote

2022-05-01 20:17 UTC, aseguragonzalez commented on src/assets/styles/donaciones.css
> +
Esta definición no es necesaria, quiero decir, no debes definir los estilos de las cabecereas

2022-05-01 20:17 UTC, aseguragonzalez commented on src/donaciones.html
> +    <link rel="stylesheet" href="assets\styles\donaciones.css" />
La ruta del fichero css es incorrecta

2022-05-01 20:17 UTC, aseguragonzalez commented on src/donaciones/checkout.html
> +    <link rel="stylesheet" href="\assets\styles\donaciones.css" />
La ruta del fichero está mal definida

2022-05-01 20:17 UTC, aseguragonzalez commented on src/donaciones/donacion-de-objetos.html
> +    <link rel="stylesheet" href="\assets\styles\donaciones.css" />
La ruta está mal definida

2022-05-01 20:17 UTC, aseguragonzalez commented on src/donaciones/donacion-de-objetos.html
> +    <script src="/assets/scripts/main.js"></script>
Este script lo estamos poniendo justo antes del cierre de la etiqueta body

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +    <link rel="stylesheet" href="assets/styles/quienes-somos.css" />
La ruta le falta empezar con /

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <div>
Este div no es necesario

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <div>
En vez de un div, puedes utilizar alguna etiqueta semántica html5

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <header>
Estructura incorrecta para la etiqueta header

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +          <p>
Estructura incorrecta para la etiqueta header

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +              <th><img src="" alt="imagen integrante" /></th>
la imagen no tiene título ni src

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +            <p>Avenida XXXXX YYYYY ZZZZZ, Población, Ciudad, CODPOST, País</p>
utiliza etiquetas semánticas como address

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <div>
No veo el sentido a la estructura de div que estás usando

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <table>
Sigo sin ver sentido que usemos una tabla para hablar de los perfiles de los miembros.

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +            <h3>centro1</h3>
Si estás copiando las tarjetas de los centros - lógico - por lo menos tienes que cambiar los nombres de cada centro

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +            <h3>centro1</h3>
No tiene sentido que en una sección uses el mapa de google map y en otra, otro mapa diferente

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <h4>Resultados en Adopciones</h4>
Propondría una estructura diferente, sobre todo teniendo en cuenta que creo que meter no es compatible con todos los navegadores: https://www.htmlquick.com/es/reference/tags/meter.html#:~:text=El%20elemento%20meter%20representa%20una%20medida%20dentro%20de,n%C3%BAmero%20de%20registros%20coincidentes%20en%20una%20consulta%2C%20etc.

2022-05-01 20:17 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <h3 class="heading">Nuestras reseñas</h3>
Toda esta sección debe estar estructurada con etiquetas HTML5 **SEMANTICAS** como ya hemos hablado

2022-05-01 22:03 UTC, palolo25 commented on src/quienes-somos.html
> +        <table>
esto me gustaria que pudiesemos hablarlo todos, a mi me parecio buena idea pero sino gustaa hago algo distinto.

2022-05-01 22:07 UTC, palolo25 commented on src/quienes-somos.html
> +            <h3>centro1</h3>
uso el mismo mapa entoces en todos

2022-05-01 22:12 UTC, palolo25 commented on src/donaciones/donacion-de-objetos.html
> +    <script src="/assets/scripts/main.js"></script>
no entiendo que quieres decir, me lo puede explicar.

2022-05-01 23:13 UTC, aseguragonzalez commented on src/donaciones/donacion-de-objetos.html
> +    <script src="/assets/scripts/main.js"></script>
Quiero decir que la referencia al fichero main.js (el script), en vez de dejarlo en la sección <head> del documento, lo estamos poniendo justo antes de la etiqueta de cierre de </body>

2022-05-02 16:15 UTC, aseguragonzalez commented on src/quienes-somos.html
> +        <table>
haz capturas de pantalla y proponlo por Slack

2022-05-15 11:48 UTC, aseguragonzalez approved these changes

2022-05-15 14:52 UTC, merged